### ISSUE TITLE
HireHendrix Link not working

### ISSUE THREAD

**Issue by mgoadric** [DiscoTrayStudios/CareerCompetencies#107]
**Describe the bug**
When visiting Career Services, the HireHendrix link is not correct.

**Screenshots**
<img width="1385" alt="Screenshot 2023-08-09 at 8 51 06 AM" src="https://github.com/DiscoTrayStudios/CareerCompetencies/assets/1328659/8cb28bcd-4dcf-4ae2-b7c3-cf37fc9c6e1b">

**Comment by mgoadric** [comment]
Unable to reproduce, need more details.

**Comment by Jqual1** [comment]
More testing done, Issue not able to be replicated. Tested Web version, app versions, and development version. All work as intended.
