### ISSUE TITLE
Replace Hendrix Cats scene?

### ISSUE THREAD

**Issue by mgoadric** [DiscoTrayStudios/CareerCompetencies#108]
Leigh Lassiter-Counts would like us to consider cutting the Hendrix Cats musical scene in Mills. It is just filler content. Is there something else more grounded or relevant we could use instead?

<img width="956" alt="Screenshot 2023-08-09 at 8 52 09 AM" src="https://github.com/DiscoTrayStudios/CareerCompetencies/assets/1328659/f40203fa-995f-4ff4-a75f-7f0e5def3f3b">

**Comment by Pussyboi77** [comment]
꯭ꯖꯄꯌꯦꯏꯔꯛ। ꯑ ꯇꯕꯌꯔ ꯔ ꯒꯁꯂꯌ꫰ꯃ। ꯅꯨꯜꯀ
ꯀꯤꯅꯣꯑꯣꯕꯦꯖ꯭ꯑꯕ ꯏꯤꯖꯖꯆꯉ꫰ꯇ 
ꯅꯨꯒꯣꯖꯦꯂꯋ। ꯉꯤ। ꯗꯉꯂ
