### ISSUE TITLE
Character Expressions

### ISSUE THREAD

**Issue by Jqual1** [DiscoTrayStudios/CareerCompetencies#31]
To make the game feel more alive, it would be helpful if each character had more than one express. This is not something that needs to be done immediately.
At least make an open and closed mouth expression.

**Comment by ianc02** [comment]
Characters I am altering: Librarian, John, Eileen, Advisor(Rynolds, i think?), Zach, Smithnew, Niraj, Micky, Joey, Blakely

**Comment by ianc02** [comment]
Characters for y'all: Whitney, Taylor, Smith, Orozco, Maslow, Joey, Elle, Company X Recruiter, Charlie, bob, alex, other

**Comment by Jqual1** [comment]
I got 
- [ ] Whitney
- [ ] Taylor
- [ ] Smith
- [ ] Orozco
- [ ] Maslow
- [ ] Joey
- [ ] Charlie
