### ISSUE TITLE
New scenes for all locations in map for every sequence

### ISSUE THREAD

**Issue by ianc02** [DiscoTrayStudios/CareerCompetencies#59]
First Map

- [x] Mills
- [x] Burrow

Second Map
- [x] Welcome Center 

Third Map
- [x] Welcome Center 
- [x] SLTC

Fourth Map

- [x] Mills 
- [x] Welcome Center (Connor)
- [x] SLTC

Fifth Map

- [x] Library
- [x] Mills (Jonathon)
- [x] Welcome Center  (Connor)
- [x] SLTC

Sixth Map

- [x] Library
- [x] Mills (Jonathon)
- [x] Welcome Center  (Connor)
- [x] SLTC

**Comment by mgoadric** [comment]
I agree. At the end of the game, there were often places with "nothing going on here." It is ok to have too many things for the players, so their choices will be more impactful. They don't all have to be super detailed with characters and conversation.

**Comment by connorescajeda** [comment]
First Map

- [Mills] 
- [Burrow]

**Comment by Jqual1** [comment]
@connorescajeda i have no idea what he means
