### ISSUE TITLE
Renpy Google Analytics

### ISSUE THREAD

**Issue by Jqual1** [DiscoTrayStudios/CareerCompetencies#66]
"I was thinking about the analytics presentation we saw in Wisconsin, do you know if Google Analytics is still a possiblity with Renpy? https://patreon.renpy.org/analytics.html" - Goadrich

**Comment by mgoadric** [comment]
Analytics and the web version do not get along. The networking is sandboxed. https://www.renpy.org/doc/html/web.html#limitations
